#!/usr/bin/env bun
/**
 * scripts/clean-test-fixtures.ts — Production Database Sanitizer & Fixture Archiver
 *
 * Scans `.eliza/vault.db` for automated test fixtures (rows with empty/null contract_addr)
 * generated by automated test suites prior to database isolation.
 *
 * STRICT SAFETY INVARIANTS:
 *  1. Default mode is strictly READ-ONLY (--dry-run).
 *  2. NEVER deletes or touches live production tokens (simulated = 0) or tokens with valid CA.
 *  3. Creates a physical file backup of `.eliza/vault.db` before performing any mutation.
 *  4. Archives full row data to `.eliza/archives/fixtures_backup_<timestamp>.json` and verifies integrity before deletion.
 *  5. Verifies post-deletion row counts (exactly 35 valid tokens preserved, $PUMPRUN intact).
 *  6. Runs VACUUM only after all verification layers pass 100%.
 */

import { Database } from "bun:sqlite";
import { DB_PATH } from "../src/db/vault.ts";
import { writeFileSync, mkdirSync, copyFileSync, statSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import { isTestFixture, isLiveDeployment } from "../src/modules/fleet/fleet-registry.ts";

const args = process.argv.slice(2);
const isDryRun = !args.includes("--archive") && !args.includes("--force");
const doArchive = args.includes("--archive") || args.includes("--force");

console.log("====================================================================");
console.log("   [+] PRODUCTION DATABASE SANITIZER & FIXTURE ARCHIVER [+]         ");
console.log("====================================================================");
console.log(`Database Path : ${DB_PATH}`);
console.log(`Mode          : ${isDryRun ? "DRY-RUN (Safe Read-Only Preview)" : "ARCHIVE & CLEAN (Live Sanitization)"}\n`);

const initialStat = statSync(DB_PATH);
const initialBytes = initialStat.size;

const db = new Database(DB_PATH);

// 1. Audit production fleet tokens (MUST BE 100% PROTECTED)
const liveTokens = db.query("SELECT COUNT(*) as count FROM deploy_logs WHERE simulated = 0 AND contract_addr IS NOT NULL AND contract_addr != ''").get() as { count: number };
const tokensWithCa = db.query("SELECT COUNT(*) as count FROM deploy_logs WHERE contract_addr IS NOT NULL AND contract_addr != ''").get() as { count: number };
const totalRows = db.query("SELECT COUNT(*) as count FROM deploy_logs").get() as { count: number };

// Verify $PUMPRUN live token exists
const pumprunCheck = db.query("SELECT id, chain, ticker, contract_addr, simulated FROM deploy_logs WHERE id = 5764").get() as any;
if (!pumprunCheck || pumprunCheck.contract_addr !== "0x7CE19E4F978009EB644c27946B47221b824C0bA3") {
  console.error("❌ CRITICAL: Live $PUMPRUN token (ID 5764) integrity check failed! Aborting.");
  db.close();
  process.exit(1);
}

// 2. Identify candidate fixtures for cleanup (automated test logs without contract address)
const fixtureQuery = "SELECT * FROM deploy_logs WHERE contract_addr IS NULL OR contract_addr = ''";
const fixtures = db.query(fixtureQuery).all() as Array<Record<string, unknown>>;

// 2B. Identify orphaned legacy test positions in active_positions (not belonging to any valid deploy_log)
const orphanedPositionsQuery =
  "SELECT * FROM active_positions WHERE contract_addr NOT IN (SELECT contract_addr FROM deploy_logs WHERE contract_addr IS NOT NULL AND contract_addr != '')";
const orphanedPositions = db.query(orphanedPositionsQuery).all() as Array<Record<string, unknown>>;

// Safety Layer: Double-check that $PUMPRUN or valid deploy_logs are NEVER flagged
for (const p of orphanedPositions) {
  if (p.contract_addr === "0x7CE19E4F978009EB644c27946B47221b824C0bA3") {
    console.error("❌ CRITICAL: Live $PUMPRUN token position flagged as orphan! Aborting.");
    db.close();
    process.exit(1);
  }
}

// Safety Layer: Double-check every candidate fixture using canonical isTestFixture predicate
for (const f of fixtures) {
  const rowObj: any = {
    id: f.id,
    chain: f.chain,
    tokenName: f.token_name,
    ticker: f.ticker,
    contractAddr: f.contract_addr,
    status: f.status,
    lifecycleState: f.lifecycle_state,
    simulated: Boolean(f.simulated),
  };
  if (!isTestFixture(rowObj)) {
    console.error(`❌ CRITICAL: Row ID ${f.id} was flagged as non-fixture by fleet-registry! Aborting.`);
    db.close();
    process.exit(1);
  }
  if (isLiveDeployment(rowObj)) {
    console.error(`❌ CRITICAL: Row ID ${f.id} matches live deployment predicate! Aborting.`);
    db.close();
    process.exit(1);
  }
}

console.log(`[1] AUDIT SUMMARY:`);
console.log(`  - Total Rows in deploy_logs       : ${totalRows.count}`);
console.log(`  - Protected Tokens with Valid CA : ${tokensWithCa.count} [PROTECTED FLEET]`);
console.log(`    (Live On-Chain: ${liveTokens.count} | Simulated: ${tokensWithCa.count - liveTokens.count})`);
console.log(`  - Disposable Test Fixtures (deploy): ${fixtures.length} (empty/null CA)`);
console.log(`  - Orphaned Legacy Positions (pos) : ${orphanedPositions.length} (test fixtures)`);
console.log(`  - Baseline Database Size         : ${(initialBytes / 1024).toFixed(2)} KB\n`);

if (fixtures.length === 0 && orphanedPositions.length === 0) {
  console.log("✅ Database is already clean! No empty test fixtures or orphaned positions found.");
  db.close();
  process.exit(0);
}

if (isDryRun) {
  console.log(`[DRY-RUN] ${fixtures.length} test fixture rows & ${orphanedPositions.length} orphaned test positions verified safe for archival.`);
  console.log(`All ${tokensWithCa.count} tokens with contract addresses will be strictly preserved.`);
  console.log("To execute physical backup, JSON archival, and database cleanup, run:");
  console.log("  bun run scripts/clean-test-fixtures.ts --archive\n");
  db.close();
  process.exit(0);
}

if (doArchive) {
  console.log("[2] EXECUTING SAFE SANITIZATION & ARCHIVAL PIPELINE:");

  // Step 2.1: Physical Database File Backup
  const timestamp = Date.now();
  const backupPath = join(process.cwd(), ".eliza", `vault.db.backup_${timestamp}`);
  copyFileSync(DB_PATH, backupPath);

  if (!existsSync(backupPath) || statSync(backupPath).size !== initialBytes) {
    console.error("❌ Physical database backup failed or size mismatch! Aborting without modifying database.");
    db.close();
    process.exit(1);
  }
  console.log(`  [+] Physical backup created: ${backupPath} (${(initialBytes / 1024).toFixed(2)} KB)`);

  // Step 2.2: Export Full Fixture Records to JSON Archive
  const archiveDir = join(process.cwd(), ".eliza", "archives");
  mkdirSync(archiveDir, { recursive: true });
  const archiveFile = join(archiveDir, `fixtures_backup_${timestamp}.json`);

  const archivePayload = {
    fixtures,
    orphanedPositions,
  };
  writeFileSync(archiveFile, JSON.stringify(archivePayload, null, 2), "utf-8");
  console.log(`  [+] Archived ${fixtures.length} deploy fixtures & ${orphanedPositions.length} positions to JSON: ${archiveFile}`);

  // Step 2.3: Verify Archive File Integrity
  const readBack = JSON.parse(readFileSync(archiveFile, "utf-8"));
  if (
    !readBack ||
    !Array.isArray(readBack.fixtures) ||
    readBack.fixtures.length !== fixtures.length ||
    !Array.isArray(readBack.orphanedPositions) ||
    readBack.orphanedPositions.length !== orphanedPositions.length
  ) {
    console.error("❌ Archive file integrity verification failed! Aborting without deleting rows.");
    db.close();
    process.exit(1);
  }
  console.log(`  [+] Archive verified: ${readBack.fixtures.length} deploy fixtures & ${readBack.orphanedPositions.length} positions parsed successfully.`);

  // Step 2.4: Snapshot Auxiliary Table Counts Before Deletion
  const tableCheckQuery = "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'";
  const tables = db.query(tableCheckQuery).all() as Array<{ name: string }>;
  const tableCountsBefore: Record<string, number> = {};
  for (const t of tables) {
    if (t.name === "deploy_logs" || t.name === "active_positions") continue;
    const cnt = (db.query(`SELECT COUNT(*) as c FROM "${t.name}"`).get() as any).c;
    tableCountsBefore[t.name] = cnt;
  }

  // Step 2.5: Execute Deletion of Empty Test Fixtures & Orphaned Positions
  if (fixtures.length > 0) {
    const deleteResult = db.run(
      "DELETE FROM deploy_logs WHERE contract_addr IS NULL OR contract_addr = ''"
    );
    console.log(`  [+] Deleted ${deleteResult.changes} empty fixture rows from deploy_logs.`);
  }

  if (orphanedPositions.length > 0) {
    const posDeleteResult = db.run(
      "DELETE FROM active_positions WHERE contract_addr NOT IN (SELECT contract_addr FROM deploy_logs WHERE contract_addr IS NOT NULL AND contract_addr != '')"
    );
    console.log(`  [+] Deleted ${posDeleteResult.changes} orphaned test position rows from active_positions.`);
  }

  // Step 2.6: Post-Deletion Verification
  const postTotal = (db.query("SELECT COUNT(*) as c FROM deploy_logs").get() as any).c;
  if (postTotal !== tokensWithCa.count) {
    console.error(`❌ Post-deletion count mismatch! Expected ${tokensWithCa.count}, got ${postTotal}. Restoring from backup...`);
    db.close();
    copyFileSync(backupPath, DB_PATH);
    console.error("Database restored from backup. Aborting.");
    process.exit(1);
  }

  // Verify $PUMPRUN is still intact
  const postPumprun = db.query("SELECT id, contract_addr FROM deploy_logs WHERE id = 5764").get() as any;
  if (!postPumprun || postPumprun.contract_addr !== "0x7CE19E4F978009EB644c27946B47221b824C0bA3") {
    console.error("❌ Post-deletion $PUMPRUN verification failed! Restoring from backup...");
    db.close();
    copyFileSync(backupPath, DB_PATH);
    process.exit(1);
  }

  // Verify all auxiliary tables are 100% unchanged
  for (const t of tables) {
    if (t.name === "deploy_logs" || t.name === "active_positions") continue;
    const cnt = (db.query(`SELECT COUNT(*) as c FROM "${t.name}"`).get() as any).c;
    if (cnt !== tableCountsBefore[t.name]) {
      console.error(`❌ Table ${t.name} count changed! Expected ${tableCountsBefore[t.name]}, got ${cnt}. Restoring from backup...`);
      db.close();
      copyFileSync(backupPath, DB_PATH);
      process.exit(1);
    }
  }
  console.log(`  [+] All ${tokensWithCa.count} valid fleet tokens verified intact ($PUMPRUN confirmed).`);
  console.log(`  [+] All ${Object.keys(tableCountsBefore).length} auxiliary tables verified unchanged.`);

  // Step 2.7: VACUUM Database to Reclaim Disk Space
  console.log("  [+] Executing VACUUM to reclaim disk space...");
  db.run("VACUUM");

  db.close();

  const finalStat = statSync(DB_PATH);
  const finalBytes = finalStat.size;
  const savedBytes = initialBytes - finalBytes;
  const savedKb = (savedBytes / 1024).toFixed(2);
  const reductionPct = ((savedBytes / initialBytes) * 100).toFixed(1);

  console.log(`\n====================================================================`);
  console.log("  ✨ DATABASE SANITIZATION & VACUUM COMPLETE");
  console.log("====================================================================");
  console.log(`  - Initial Size : ${(initialBytes / 1024).toFixed(2)} KB`);
  console.log(`  - Final Size   : ${(finalBytes / 1024).toFixed(2)} KB`);
  console.log(`  - Space Saved  : ${savedKb} KB (-${reductionPct}%)`);
  console.log(`  - Final Rows   : ${postTotal} active fleet tokens in deploy_logs`);
  console.log(`  - Backup File  : ${backupPath}`);
  console.log(`  - Archive File : ${archiveFile}`);
  console.log("====================================================================\n");
}
